language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
env:
  - PROJECT='-p core' JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
  - PROJECT='-p consumer' JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
  - PROJECT='-p provider' JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
  - PROJECT='-p pact-specification-test' JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
script:
  - unset _JAVA_OPTIONS
  - ./gradlew --version
  - ./gradlew --stacktrace --no-daemon $PROJECT build
install: true
