# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

build: false

build_script:
  - set JAVA_HOME=C:\Program Files\Java\jdk11
  - java -version
  - gradlew --version
  - gradlew --stacktrace --no-daemon -i check -x :consumer:pact-jvm-consumer-junit:clojureTest -x :pact-jvm-provider-lein:clojureTest
