# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

build: false

build_script:
  - set JAVA_HOME=C:\Program Files\Java\jdk13
  - java -version
  - gradlew --version
  - gradlew --stacktrace --no-daemon -i check -Djna.nosys=true
